### ISSUE TITLE
Save a workspace, exit, restart BinJr, load workspace: the window has grown slightly larger

### ISSUE THREAD

**Issue by xrysf03** [binjr/binjr#156] opened 2024-10-18 10:00 UTC
This is just a very minor observation, I hesitate to call this a complaint...
BTW I'd like to *praise* BinJr for working well with multi-diplay setups in Windows. BinJr tends to follow the display that I used the last time very well (unlike a number of other software pieces).

To the point / reproduction recipe:

- Maximize BinJr on the current display. It will fit precisely.
- Save your work into a .bjr file.
- Exit BinJr.
- Start BinJr again, reloading the stored .bjr file (e.g. by association, clicking the .bjr file in "file explorer")
- BinJr will reopen on the correct display
- Note that BinJr will reopen windowed, matching the size of the display (not maximized)
- The BinJr window will overlap the current display by just a few pixels.
- If you continue to work, save your work, and reload from file, this growth will repeat - and in a multi-display setup, you'll start to see the border of the window on the neighboring displays.
- Grows both horizontally and vertically.

If I'm aware of this, a simple countermeasure is, to click the "maximize" button each time after re-opening the file. After that, any later save will re-set the previous "cumulative growth" (and maybe store one initial "growth step") in the newly saved file.
It's almost as if BinJr reads the window position and size upon saving the file, and tries to post-compensate the window border, which may or may not be needed, depending on OS platform... Or asks the window manager to restore the saved window dimensions upon startup / loading the file, and the "get dimensions" and "set dimensions" functions are not equivalent in their treatment of the window border...

Freshly observed in BinJr 3.20.0-pre (Github says uploaded 2 days ago) and before it in several previous releases over the last 6 months or so. This is all in Windows 10, the OS is kept up to date.

Again this is just a very minor glitch - especially minor now that I don't have to restart BinJr just to reload the CSV data. Ctrl+F5 rules.

**Comment by fthevenet** [comment] 2024-10-22 12:11
I have managed to reproduced the problem on Windows under a set of very specific circumstances:
* Running more than one monitors
* Each of the monitors have different scale factors (i.e. one is set to 125%, the other 100% for the other)
* The main window for binjr is opened, closed and restored on _a monitor other than the one marked as "main display"_

Under these conditions, if the main display's scaling is bigger than the secondary's (where binjr is opened/closed), then the main window will grow slightly each time is it restored.
If the scaling of the main display is smaller than the secondary display, however, the main window will shrink each time is is restored.
If binjr is started and restored on the main display, then it work as intended.

The reason for that, is that while the UI for the app itself adapts to the scaling factor used on the monitors where it is displayed dynamically, the title bar and window decorations *do not* and are always using the scaling factor for the main display, which means that when it is either too big or too small when displayed on a secondary monitor with a different scale.
This in turn causes reporting of the window size in such conditions to be off by the diff in title bar size between the two monitors, and therefore when the window is restored using these stored coordinates, it is appears to have moved.

The proper way to fix that would be to address the issue in JavaFX, so that a window's title bar is resized properly when the window changes display.
One possible workaround could be to try to detect the discrepancy in scaling factors for the app and the window and account for it in the code that saves and restore the window's position.
Another one would be to use an undecorated window, and implement a custom title bar in-app.

Meanwhile, could you please confirm whether or not you were running under similar conditions when you noticed the problem? Thanks.

**Comment by fthevenet** [comment] 2024-10-22 12:34
Please also note that if the app was maximized when it was closed, it will always be restored as floating window the size of the screen, not as a fixed, maximized window.
This is a known limitation (binjr only stores the coordinates of the window, not its state and therefore cannot restore it), but likely unrelated to the reported issue.

**Comment by xrysf03** [comment] 2024-10-22 13:07
Man you rock! How have you managed to pinpoint the exotic problem with this accuracy.
That's indeed my precise scenario. I prefer lower DPI displays, but my notebook comes with this hip high-DPI full-HD screen. Hence my mixed set of monitors.
The Windows multi-display and multi-DPI mixture is indeed a mess, in general. Even stuff like MS own RDP client/server have trouble coping with this.
I suggest that we just let it be in BinJr :-)
Thank you

**Comment by fthevenet** [comment] 2024-10-23 08:40
So it turns out that my initial analysis mixed up two separate issues.
The first one, the title bar for the main window always being scaled according to the parameters for the main display, even when moved to a secondary display using a different scaling factor, was in fact due to the custom executable used to bootstrap the JVM not properly opting into HiDPI feature introduced in Windows 10.
This was easily addressed and now the title bar is properly scaled on any monitor the app is displayed. As an added bonus, this also gets rid of a glitch where the splashscreen would get resized a few seconds before it is discarded, when the main display's scale is not 100%. So this is nice! 🙂 

However, all this had no effect on the issue reported here. The root cause is indeed lying deep into JavaFX and triggered because the window is being initiated on the main screen *before* becoming visible, set new boundaries and then rendered visible. At that point the window is being displayed on the target screen, but with some of its properties having been calculated with the assumption it would show on the main screen, which then causes the coordinate calculation to be off by a few pixels when rendered.
Given the very specific circumstances for the issue to appear and the complexity of the code involved, I feel fixing the issue upstream is too much risk and work for too little benefits. 
Thankfully, it"s quite easy to work around it, by just setting the saved window's coordinates once again *after* the window has been made visible; because it is only off be a few pixels, I find the visible glitches could have caused to be minimal or even non-existent.

At least that was an interesting one... 😅

**Closed as completed by fthevenet** 2024-10-23 08:40 UTC
Labels: bug
