### ISSUE TITLE
How do I parse bog-standard syslog format?

### ISSUE THREAD

**Issue by PenelopeFudd** [binjr/binjr#124] opened 2023-02-20 08:23 UTC
New user here.

I'm trying to read standard Linux system log files, lines that start with `Feb 20 00:16:38 some log message here`.

As you can see, it doesn't have the year.
![image](https://user-images.githubusercontent.com/1606480/220050324-23b5a33e-b3c3-4a20-a73e-a8edef548e65.png)

And when I add it to a new worksheet, it says the time range is from 1969-02-28 3:59:59 pm to 1969-02-28 4:00:00 pm.

This does not seem normal.  :-/

![image](https://user-images.githubusercontent.com/1606480/220051337-d2ecad8d-0162-4e02-b1ba-b65d6515adaf.png)

**Comment by fthevenet** [comment] 2023-02-20 13:55
There are maybe a couple of things at play here.

First of all, as you've mentioned, the source data is missing the year information, so binjr has to complete the elements its got with a default starting point in time, as it cannot deal with partial dates.
For better or worse, the default date I have chosen is 1970-01-01 00:00:00.000 UTC, which is 1969-12-31 16:00:00.000 (4pm) in your timezone (UTC-8).

So this explains why the year shown here is 1969: because the year component for the date was not provided, 1969 is used as a substitute while the day and month are overridden with the data parsed from the file.

With that said, even with this does not explain why the time components are not overridden (e.g. it says 4 p.m instead of 12 a.m.). I could not reproduce this with the parsing rules that you shared above, but this is however what you you get with parsing rules that only picked up the month and day, like such:
![image](https://user-images.githubusercontent.com/7450507/220125486-8c8d126a-f9df-4537-805e-80dda53bceb9.png)

Is it possible at all that the two screenshots do not actually match (e.g. the log view in the second screenshot was taken with a version of the parsing rules that does not capture the time)?

If not, then there is probably a bug in binjr, but as I said I could not reproduce it.

**Comment by PenelopeFudd** [comment] 2023-02-20 21:14
Created this logfile: 
```
Feb 19 00:00:01 thinkpad systemd[1]: Starting system activity accounting tool...
Feb 19 00:00:01 thinkpad audit: BPF prog-id=739 op=LOAD
Feb 19 00:00:01 thinkpad audit: BPF prog-id=740 op=LOAD
Feb 19 00:00:01 thinkpad systemd[1]: Starting update of the root trust anchor for DNSSEC validation in unbound...
```
Fresh screenshot of freshly-imported log file in a new worksheet:
![image](https://user-images.githubusercontent.com/1606480/220197755-01cc3de2-8474-4e40-a4ae-2cad25c1f46c.png)

I'd argue that the syslog format should have a year on it, but it's been sacrificed in the name of backwards-compatibility.  
I would also argue that when there isn't a year, we should try to follow syslog's algorithm and assume the timestamp is for some moment in the past 365.26 days, with an option for users to override that.

If they've got a logfile containing multiple years' worth of entries, it's tougher: assume the file ends in the most recent 365.26-day period, and extrapolate backwards, assuming that there's at least one log entry per month and the timestamps are in monotonically increasing order.  The filesystem timestamp of the logfile might be worth considering too: if it's roughly the same as the last log entry in the file (logrotation+compression effect), copy the year from it.

Although at some point, this turns into a data forensics problem.  :-)

**Comment by PenelopeFudd** [comment] 2023-02-20 21:17
BTW, I changed the last line in the logfile to be `Feb 19 00:00:03` to see if the problem was caused by all the entries having the same timestamp, but it didn't help, the time range at the top of the worksheet was still 1969-02-08 3:59:59pm to 4:00:00pm.

It's odd that it's grabbing Feb 8th, and not Feb 20th or Jan 1st.

BTW, this is Binjr 3.11.0, downloaded yesterday.

**Comment by fthevenet** [comment] 2023-03-13 15:19
I have created two separate issues to track the problems that surfaced in this one:

- [#129 - Let users choose the date & time that serves as an anchor to construct timestamps for partial data](https://github.com/binjr/binjr/issues/129) to track making the default time reference point user-selectable
- [130 - Different behaviour when typing the name of a TemporalCaptureGroup or selecting it from the dropdown list in profile editor](https://github.com/binjr/binjr/issues/130) to track the bug that was the root cause for some parsing keyword not working (and the source of much confusion)

@PenelopeFudd I'm therefore closing this issue; feel free to reopen it if you feel there's a need.

**Closed as completed by fthevenet** 2023-03-13 15:19 UTC
Labels: discussion
